chore(test/docs): add tests for CI and add README.md

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -64,3 +64,26 @@ jobs:
 
       - name: Turbo Build
         run: pnpm turbo run build --filter=@pokemetrix/damage-calc
+
+      - name: Install nextest
+        uses: taiki-e/install-action@nextest
+
+      - name: Test WebAssembly (Chrome)
+        run: wasm-pack test --headless --chrome packages/damage-calc
+
+      - name: Test WebAssembly (Firefox)
+        run: wasm-pack test --headless --firefox packages/damage-calc
+
+      - name: Test Rust (cargo nextest)
+        run: cargo nextest run --profile ci --workspace
+
+      - name: Test Next.js (Vitest)
+        run: pnpm --filter @pokemetrix/app run test:ci
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if tests fail
+        with:
+          report_paths: '**/junit.xml,**/test-results/*.xml'
+          check_name: 'JUnit Test Report'
+
